Loading data in pandas

In [1]:
import pandas as pd

df = pd.read_csv('Pokemon.csv')

# df = pd.read_excel   //for excel

# df = pd.read_csv('pokemon.txt', delimiter='\t')  //for tab seperated data files in txt form   //delimiter works as what to seperate data

# print (df.head(3))

# print (df.tail(3))

Reading Data In pandas

In [2]:
### read header
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [3]:
### for each column reading
df.columns
print(df['Name'])

# for multiple columns
# print(df[['Name'], ['Type 1'], ['HP']])

# also works
# print(df.Name)

# print(df['Name'][0:5])
# gives only first five columns

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [4]:
###read each specific row
# print(df.iloc[1])

# for multiple rows
print(df.iloc[0:4])

   #                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49
1  2                Ivysaur  Grass  Poison    405  60      62       63
2  3               Venusaur  Grass  Poison    525  80      82       83
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
0       65       65     45           1      False
1       80       80     60           1      False
2      100      100     80           1      False
3      122      120     80           1      False

In [5]:
##for specific row and column (R, C)

print(df.iloc[2,1])

Venusaur

In [6]:
# for index, row in df.iterrows():
#     print(index, row)

# for index, row in df.iterrows():
#     print(index, row['HP'])

In [7]:
# for specific condition

df.loc[df['Type 1'] == 'Grass']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False

In [8]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [9]:
# sorting

# df.sort_values('Name', ascending=False)

# df.sort_values(['Type 1', 'HP'], ascending=False)

df.sort_values(['Type 1', 'HP'], ascending=[1, 0])
# makes type 1 go from a to z and hp from high to low

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,500,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,600,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,295,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,340,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,200,20,15,20,10,55,80,3,False

Making CHanges to data

In [10]:
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [11]:
# df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']
# df = df.drop(columns = ['Total'])

df['Total'] = df.iloc[:,4:10].sum(axis=1)

# end parameter in list is exclusive, 10 means 10th column is the one we dont include
# iloc[all rows, list of columns].sum(axis=1(horizaontally), axis=0(vertically)]



df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,591,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,750,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,970,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,1170,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,553,39,52,43,60,50,65,1,False

Saving to external

In [12]:
# df.to_csv('modified.csv', index=False)

# df.to_excel('modified.xlsx', index=False)

df.to_csv('modified.txt', index=False, sep='\t')

Filtering of data

In [13]:
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] > 50)]

new_df.to_csv('modfied1.csv')

after shrinking a data into new dataset, the index is damaged

Reset Index

In [14]:
new_df = new_df.reset_index()
new_df

,index,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,2,Ivysaur,Grass,Poison,750,60,62,63,80,80,60,1,False
1,2,3,Venusaur,Grass,Poison,970,80,82,83,100,100,80,1,False
2,3,3,VenusaurMega Venusaur,Grass,Poison,1170,80,100,123,122,120,80,1,False
3,49,44,Gloom,Grass,Poison,750,60,65,70,85,75,40,1,False
4,50,45,Vileplume,Grass,Poison,930,75,80,85,110,90,50,1,False
5,76,70,Weepinbell,Grass,Poison,725,65,90,50,85,45,55,1,False
6,77,71,Victreebel,Grass,Poison,910,80,105,65,100,70,70,1,False
7,452,407,Roserade,Grass,Poison,940,60,70,65,125,105,90,4,False
8,651,590,Foongus,Grass,Poison,573,69,55,45,55,55,15,5,False
9,652,591,Amoonguss,Grass,Poison,898,114,85,70,85,80,30,5,False

In [15]:
new_df1 = new_df

In [16]:
new_df1

,index,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,2,Ivysaur,Grass,Poison,750,60,62,63,80,80,60,1,False
1,2,3,Venusaur,Grass,Poison,970,80,82,83,100,100,80,1,False
2,3,3,VenusaurMega Venusaur,Grass,Poison,1170,80,100,123,122,120,80,1,False
3,49,44,Gloom,Grass,Poison,750,60,65,70,85,75,40,1,False
4,50,45,Vileplume,Grass,Poison,930,75,80,85,110,90,50,1,False
5,76,70,Weepinbell,Grass,Poison,725,65,90,50,85,45,55,1,False
6,77,71,Victreebel,Grass,Poison,910,80,105,65,100,70,70,1,False
7,452,407,Roserade,Grass,Poison,940,60,70,65,125,105,90,4,False
8,651,590,Foongus,Grass,Poison,573,69,55,45,55,55,15,5,False
9,652,591,Amoonguss,Grass,Poison,898,114,85,70,85,80,30,5,False

In [17]:
new_df1 = new_df1.reset_index(drop=True)
new_df1

,index,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,2,Ivysaur,Grass,Poison,750,60,62,63,80,80,60,1,False
1,2,3,Venusaur,Grass,Poison,970,80,82,83,100,100,80,1,False
2,3,3,VenusaurMega Venusaur,Grass,Poison,1170,80,100,123,122,120,80,1,False
3,49,44,Gloom,Grass,Poison,750,60,65,70,85,75,40,1,False
4,50,45,Vileplume,Grass,Poison,930,75,80,85,110,90,50,1,False
5,76,70,Weepinbell,Grass,Poison,725,65,90,50,85,45,55,1,False
6,77,71,Victreebel,Grass,Poison,910,80,105,65,100,70,70,1,False
7,452,407,Roserade,Grass,Poison,940,60,70,65,125,105,90,4,False
8,651,590,Foongus,Grass,Poison,573,69,55,45,55,55,15,5,False
9,652,591,Amoonguss,Grass,Poison,898,114,85,70,85,80,30,5,False

Regex filter ( textual patterns)

In [18]:
df.loc[df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,1170,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,1168,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,1168,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,1182,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,845,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,1037,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,1030,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,1150,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,1070,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,1080,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,1095,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,1199,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,1080,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,1430,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,1420,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,970,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,1175,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,1190,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,1125,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,1125,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,1085,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,1329,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,1115,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,1160,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,1200,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,1136,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,940,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,910,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,1210,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,920,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,1015,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,1015,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,1100,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,1100,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,1035,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,1015,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,1060,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,1280,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,1290,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,1290,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,1290,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,1445,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,1025,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,1308,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,1138,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,1158,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,1126,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,1040,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,1290,50,160,110,160,110,110,6,True

In [19]:
df.loc[~df['Name'].str.contains('Mega')]
# not containing mega

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,591,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,750,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,970,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,553,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,730,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,1105,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,1150,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,1130,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,1280,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,1130,80,110,120,130,90,70,6,True

In [20]:
import re

# df.loc[df['Type 1'].str.contains('Fire|Grass', regex=True)]
# this needs capitalization

# df.loc[df['Type 1'].str.contains('fire|grass', flags = re.I, regex=True)]
# flags = re.I removes need of exact capitalization in the result

# df.loc[df['Name'].str.contains('Pi[a-z]*', flags = re.I, regex=True)]
df.loc[df['Name'].str.contains('^Pi[a-z]*', flags = re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,446,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,627,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,857,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,1037,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,550,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,915,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,1095,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,350,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,565,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,850,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,588,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,781,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,485,50,55,50,36,30,43,5,False

Conditional Changes

In [22]:
# df.loc[df['Type 1'] == 'Fire' , 'Type 1'] = 'Flamer'

# df

df.loc[df['Type 1'] == 'Flamer' , 'Type 1'] = 'Fire'

df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,591,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,750,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,970,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,1170,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,553,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,1150,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,1290,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,1130,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,1280,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,1130,80,110,120,130,90,70,6,True

Aggregate Statistics (Group By)

In [28]:
df.groupby(['Type 1']).mean().sort_values('Defense', ascending=False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Steel,442.851852,920.148148,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Rock,392.727273,851.590909,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Dragon,474.375000,1018.031250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Ground,356.281250,811.093750,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ghost,486.500000,814.781250,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Water,303.089286,794.946429,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ice,423.541667,803.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Grass,344.871429,780.357143,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Bug,334.492754,696.173913,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,461.354839,815.322581,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Poison,251.785714,734.714286,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Fire,327.403846,841.711538,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Psychic,380.807018,870.403509,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Electric,363.500000,802.318182,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Flying,677.750000,867.500000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Fighting,363.851852,766.814815,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fairy,449.529412,777.764706,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Normal,319.173469,731.816327,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408

In [33]:
# df.groupby(['Type 1']).mean().sort_values('Attack', ascending=False)
# df.groupby(['Type 1']).mean().sort_values('HP', ascending=False)
df.groupby(['Type 1']).mean().sort_values('Speed', ascending=False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Flying,677.750000,867.500000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Electric,363.500000,802.318182,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Dragon,474.375000,1018.031250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Psychic,380.807018,870.403509,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Dark,461.354839,815.322581,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Fire,327.403846,841.711538,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Normal,319.173469,731.816327,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Fighting,363.851852,766.814815,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Water,303.089286,794.946429,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ghost,486.500000,814.781250,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Ground,356.281250,811.093750,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Poison,251.785714,734.714286,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Ice,423.541667,803.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Grass,344.871429,780.357143,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Bug,334.492754,696.173913,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Rock,392.727273,851.590909,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,920.148148,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Fairy,449.529412,777.764706,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824

In [35]:
df.groupby(['Type 1']).sum()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Bug,23080,48036,3925,4897,4880,3717,4471,4256,222,0
Dark,14302,25275,2071,2740,2177,2314,2155,2361,125,2
Dragon,15180,32577,2666,3588,2764,3099,2843,2657,124,12
Electric,15994,35302,2631,3040,2917,3961,3243,3718,144,4
Fairy,7642,13222,1260,1046,1117,1335,1440,826,70,1
Fighting,9824,20704,1886,2613,1780,1434,1747,1784,91,0
Fire,17025,43769,3635,4408,3524,4627,3755,3871,167,5
Flying,2711,3470,283,315,265,377,290,410,22,2
Ghost,15568,26073,2062,2361,2598,2539,2447,2059,134,2
Grass,24141,54625,4709,5125,4956,5425,4930,4335,235,3
Ground,11401,25955,2361,3064,2715,1807,2008,2045,101,4
Ice,10165,19283,1728,1746,1714,1861,1831,1523,85,2
Normal,31279,71718,7573,7200,5865,5470,6245,7012,299,2
Poison,7050,20572,1883,2091,1927,1692,1803,1780,71,0
Psychic,21706,49613,4026,4073,3858,5609,4918,4645,193,14
Rock,17280,37470,2876,4086,4435,2787,3321,2460,152,4
Steel,11957,24844,1761,2503,3412,1823,2177,1492,104,4
Water,33946,89034,8071,8305,8170,8379,7898,7388,320,4

In [43]:
# df.groupby(['Type 1']).count()
df['count']=1
df.groupby(['Type 1', 'Type 2']).count()['count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: count, Length: 136, dtype: int64